name: "CodeQL Bundle: Download bundle"
description: "Action to download a GitHub provided CodeQL bundle that can be customized"
inputs:
  tag:
    description: "The tag of the bundle to download"
    required: true
    default: "latest"
  platforms:
    description: "A comma-separated list of platforms to download the bundle for, options are: osx64, linux64, win64"
    required: true
    default: ""
  token:
    description: "A GitHub token to use for downloading the bundle"
    required: true
    default: ${{ github.token }}
outputs:
  bundle-path:
    description: Path to the downloaded bundle
    value: ${{ steps.download-bundle.outputs.bundle-path }}
runs:
  using: "composite"
  steps:
    - id: download-bundle
      shell: bash
      env:
        TAG: ${{ inputs.tag }}
        PLATFORMS: ${{ inputs.platforms }}
        RUNNER_TEMP: ${{ runner.temp }}
        GH_TOKEN: ${{ inputs.token }}
      run: |
        #!/bin/bash

        set -e

        output_path=${RUNNER_TEMP}/codeql-bundle.tar.gz
        platforms=()
        if [[ -n ${PLATFORMS} ]]; then
            for platform in $(echo $PLATFORMS | tr ',' ' '); do
                platforms+=("${platform}")
            done
        fi

        if [[ ${TAG} -ne "latest" ]]; then
            opts+=("${TAG}")
        fi

        if [[ ${#platforms[@]} -eq 1 ]]; then
            opts+=("--pattern codeql-bundle-${platforms[0]}.tar.gz")
        else
            opts+=("--pattern codeql-bundle.tar.gz")
        fi

        opts+=("--output ${output_path}")

        echo "::group::Downloading CodeQL bundle"
        gh release download --repo github/codeql-action ${opts[@]}
        echo "::endgroup::"

        echo "bundle-path=${output_path}" >> $GITHUB_OUTPUT