name: "CodeQL Bundle"
description: "Action to build custom CodeQL bundles"
inputs:
  bundle-version:
    description: The tag of bundle release to customize (e.g., codeql-bundle-20220311)
    required: false
    default: latest
  repository:
    description: The organization and repository from which to fetch the bundle to be customized. Specified as "org/repo".
    required: false
    default: "github/codeql-action"
  host:
    description: The GitHub host from which to fetch the bundle to be customized.
    required: false
  platform:
    description: "Specify which bundle platform to customize. Options are: 'linux64', 'osx64', 'win64', 'multi-platform'. The default is 'multi-platform'."
    required: false
    default: "multi-platform"
  packs:
    description: A comma-separated list of CodeQL packs to include in the bundle
    required: true
  workspace:
    description: Root directory where the codeql-workspace.yml file is located
    required: false
    default: "."
  upload:
    description: Upload the created bundle
    required: false
    default: "true"
  token:
    default: ${{ github.token }}
  concurrency-limit:
    description: The max number of packs that will be processed concurrently
    required: false
    default: "2"
outputs:
  artifact-name:
    description: "Name of the artifact containing the uploaded bundle"
  bundle-path:
    description: Path to the created bundle
  bundle-tag:
    description: The tag of the bundle that is customized
runs:
  using: "node16"
  main: "./lib/codeql-bundle-action.js"
