name: "Test CodeQL Bundle: Create bundle"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
            gh release download codeql-bundle-v2.14.0 --repo github/codeql-action --pattern codeql-bundle.tar.gz --dir ${RUNNER_TEMP}
        env:
          GH_TOKEN: ${{ github.token }}
      - uses: advanced-security/codeql-bundle-action/create-bundle@main
        id: create-bundle
        with:
          bundle-path: ${{ runner.temp }}/codeql-bundle.tar.gz
          packs: "test/go-queries,test/go-customizations,test/java-queries,test/cpp-queries,test/javascript-queries" 
          workspace: "${{ github.workspace }}/tests/codeql-workspace.yml"
          default-code-scanning-config: "${{ github.workspace }}/tests/code-scanning-config.yml"
          platforms: "osx64,linux64,win64"
      - uses: actions/upload-artifact@v3
        with:
          name: codeql-bundles
          path: ${{ steps.create-bundle.outputs.output-path }}