name: "Test CodeQL Bundle: Create bundle"
on:
  workflow_dispatch:

jobs:
  test:
    name: "Create custom bundle"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: advanced-security/codeql-bundle-action/download-bundle@v2
        id: download-bundle
        with:
          tag: "latest"
          platforms: "osx64,linux64,win64"
      - uses: advanced-security/codeql-bundle-action/create-bundle@v2
        id: create-bundle
        with:
          bundle-path: ${{ steps.download-bundle.outputs.bundle-path }}
          packs: "test/go-queries,test/go-customizations,test/java-queries,test/cpp-queries,test/javascript-queries" 
          workspace: "${{ github.workspace }}/tests/codeql-workspace.yml"
          default-code-scanning-config: "${{ github.workspace }}/tests/code-scanning-config.yml"
          platforms: "osx64,linux64,win64"
          debug: "true"
      - uses: actions/upload-artifact@v3
        with:
          name: codeql-bundles
          path: ${{ steps.create-bundle.outputs.output-path }}